apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stellar-insights-mainnet

bases:
- ../../

namePrefix: mainnet-

commonLabels:
  environment: mainnet

images:
- name: stellar-insights/backend
  newTag: mainnet
- name: stellar-insights/frontend
  newTag: mainnet

configMapGenerator:
- name: stellar-insights-config
  behavior: merge
  literals:
  - stellar-network=mainnet
  - rust-log=warn
  - cors-allowed-origins=https://app.stellar-insights.com
