apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payraider-backend-data
  namespace: payraider
  labels:
    app: payraider
    component: backend
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
