apiVersion: v1
kind: ConfigMap
metadata:
  name: payraider-frontend-config
  namespace: payraider
  labels:
    app: payraider
    component: frontend
data:
  api-url: "http://payraider-backend:8080"
