apiVersion: v1
kind: Service
metadata:
  name: payraider-frontend
  namespace: payraider
  labels:
    app: payraider
    component: frontend
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app: payraider
    component: frontend
