apiVersion: v1
kind: Namespace
metadata:
  name: payraider
  labels:
    name: payraider
    environment: production
    app: payraider
  annotations:
    description: "PayRaider application namespace"
