apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payraider-staging

bases:
- ../../

namePrefix: staging-

commonLabels:
  environment: staging

patches:
- path: backend-replicas.yaml
- path: frontend-replicas.yaml

images:
- name: payraider/backend
  newTag: staging
- name: payraider/frontend
  newTag: staging

configMapGenerator:
- name: payraider-config
  behavior: merge
  literals:
  - stellar-network=testnet
  - rust-log=info
  - cors-allowed-origins=https://staging.payraider.com
